### ISSUE TITLE
Open pdfs in PdfConverter

### ISSUE THREAD

**Issue by jnguyen1192** [robindabird/PdfPageByPage#1]
I realize that we can open a pdf file.

When we **drag and drop a pdf file in PdfConverter**, we can **open the pdf with Microsoft Word**.

Then, we can save as a new file to **modify the PDF**.

**Comment by gliatti** [comment]
Converting a PDF file is no longer possible. The application will do nothing

**Comment by jnguyen1192** [comment]
When I try to drop the file,

At the second time,

It's always possible to modify the pdf in Word

**Comment by gliatti** [comment]
Thanks, I made a mistake during the push action. Didn't not push the last version of FileExtension.cs
